import { createHash } from "crypto";
import { execSync } from "child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "fs";
import { join, relative, resolve } from "path";
export interface GitSnapshot { commit: string; status: string; files: string[]; gitRoot?: string; subRepos?: string[]; fileHashes?: Record<string, string>; }
function hashText(value: string): string { return createHash("sha256").update(value).digest("hex"); }
function statusFiles(status: string): string[] { return status.split("\n").map((line) => line.trimEnd()).filter(Boolean).map((line) => { const payload = line.slice(3).trim(); return payload.includes(" -> ") ? payload.split(" -> ").at(-1)! : payload; }); }
function fileStateHash(root: string, file: string): string { try { const full = resolve(root, file); if (existsSync(full) && statSync(full).isFile()) return hashText(readFileSync(full, "utf-8")); } catch {} try { return hashText(execSync(`git diff HEAD -- ${JSON.stringify(file)}`, { cwd: root, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] })); } catch { return ""; } }
export function findGitRoot(cwd: string): string | null { try { return execSync("git rev-parse --show-toplevel", { cwd, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] }).trim(); } catch { return null; } }
export function findGitRepositories(cwd: string): string[] { const root = findGitRoot(cwd); if (root && resolve(root) === resolve(cwd)) return [root]; const repos: string[] = []; try { for (const entry of readdirSync(cwd)) { if (entry === "node_modules" || entry === ".git") continue; const fullPath = join(cwd, entry); try { if (statSync(fullPath).isDirectory() && existsSync(join(fullPath, ".git"))) repos.push(fullPath); } catch {} } } catch {} if (repos.length > 0) return repos; if (root) return [root]; return repos; }
function snapshotSingleRepo(root: string): GitSnapshot { let commit = "unknown"; try { commit = execSync("git rev-parse HEAD", { cwd: root, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] }).trim(); } catch {} let status = ""; try { status = execSync("git status --porcelain=v1 -uall", { cwd: root, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] }); } catch {} const files = statusFiles(status); const fileHashes: Record<string, string> = {}; for (const file of files) fileHashes[file] = fileStateHash(root, file); return { commit, status, files, gitRoot: root, subRepos: [root], fileHashes }; }
export function snapshotGit(cwd: string): GitSnapshot { const repos = findGitRepositories(cwd); if (repos.length === 0) return { commit: "unknown", status: "", files: [], gitRoot: undefined, subRepos: [] }; if (repos.length === 1) return snapshotSingleRepo(repos[0]); const allFiles: string[] = []; const statusLines: string[] = []; const commits: string[] = []; const fileHashes: Record<string, string> = {}; for (const repo of repos) { const relPrefix = relative(cwd, repo); const snap = snapshotSingleRepo(repo); commits.push(`${relPrefix}:${snap.commit.slice(0, 7)}`); for (const line of snap.status.split("\n").filter(Boolean)) statusLines.push(`${line.slice(0, 3)}${relPrefix}/${line.slice(3).trim()}`); for (const file of snap.files) { const key = `${relPrefix}/${file}`; allFiles.push(key); fileHashes[key] = snap.fileHashes?.[file] || ""; } } return { commit: commits.join(", ") || "multi-repo", status: statusLines.join("\n"), files: allFiles, gitRoot: cwd, subRepos: repos, fileHashes }; }
function committedFiles(root: string, beforeCommit: string): string[] { if (!beforeCommit || beforeCommit === "unknown") return []; try { return execSync(`git diff --name-only ${beforeCommit} HEAD`, { cwd: root, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] }).split("\n").map((x) => x.trim()).filter(Boolean); } catch { return []; } }
export function diffWorkerChanges(cwd: string, before: GitSnapshot): { filesChanged: string[]; diffSummary: string; rawDiff: string } { const repos = before.subRepos && before.subRepos.length > 0 ? before.subRepos : findGitRepositories(cwd); if (repos.length === 0) return { filesChanged: [], diffSummary: "No git repositories found in workspace", rawDiff: "" }; const allFilesChanged: string[] = []; const summaryParts: string[] = []; let combinedRawDiff = ""; for (const repo of repos) { const relPrefix = repos.length > 1 ? relative(cwd, repo) : ""; const repoBeforeFiles = new Set<string>(); for (const f of before.files) repoBeforeFiles.add(repos.length > 1 ? f.slice(`${relPrefix}/`.length) : f); const currentStatus = (() => { try { return execSync("git status --porcelain=v1 -uall", { cwd: repo, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] }); } catch { return ""; } })(); const currentFiles = statusFiles(currentStatus); const changed = new Set<string>(); for (const file of committedFiles(repo, repos.length === 1 ? before.commit : "unknown")) changed.add(file); for (const file of currentFiles) { const currentHash = fileStateHash(repo, file); const beforeKey = repos.length > 1 ? `${relPrefix}/${file}` : file; const beforeHash = before.fileHashes?.[beforeKey]; if (!repoBeforeFiles.has(file) || beforeHash !== currentHash) changed.add(file); } for (const file of changed) { const display = relPrefix ? `${relPrefix}/${file}` : file; if (!allFilesChanged.includes(display)) allFilesChanged.push(display); } try { const diffStat = execSync("git diff --stat HEAD", { cwd: repo, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] }).trim(); const committedStat = repos.length === 1 && before.commit !== "unknown" ? execSync(`git diff --stat ${before.commit} HEAD`, { cwd: repo, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] }).trim() : ""; const stat = [committedStat, diffStat].filter(Boolean).join("\n"); if (stat) summaryParts.push(relPrefix ? `[${relPrefix}]:\n${stat}` : stat); } catch {} try { let raw = ""; if (repos.length === 1 && before.commit !== "unknown") raw += execSync(`git diff ${before.commit} HEAD`, { cwd: repo, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] }); raw += execSync("git diff HEAD", { cwd: repo, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] }); raw += execSync("git diff --cached", { cwd: repo, encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] }); if (raw) combinedRawDiff += (relPrefix ? `\n# Diff for ${relPrefix}\n` : "") + raw; } catch {} } return { filesChanged: allFilesChanged, diffSummary: summaryParts.join("\n\n") || (allFilesChanged.length > 0 ? `${allFilesChanged.length} file(s) changed by worker` : "No worker git changes"), rawDiff: combinedRawDiff.slice(0, 16000) }; }
export function ensureLocalGitExclude(repoRoot: string, entry = ".pi-live.md"): boolean { try { const gitDir = join(repoRoot, ".git"); if (!existsSync(gitDir) || !statSync(gitDir).isDirectory()) return false; const infoDir = join(gitDir, "info"); const excludeFile = join(infoDir, "exclude"); if (!existsSync(infoDir)) mkdirSync(infoDir, { recursive: true }); const existing = existsSync(excludeFile) ? readFileSync(excludeFile, "utf-8") : ""; if (existing.split("\n").map((l) => l.trim()).includes(entry)) return false; writeFileSync(excludeFile, existing ? `${existing.trimEnd()}\n${entry}\n` : `${entry}\n`, "utf-8"); return true; } catch { return false; } }
